# Generated by Django 5.2.9 on 2025-12-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
