# Generated by Django 6.0 on 2025-12-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('uom_type', models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('unit', 'Unit/Piece'), ('time', 'Time')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='SKU/Product Code', max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('product_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good'), ('semi_finished', 'Semi-Finished'), ('consumable', 'Consumable'), ('service', 'Service')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('purchase_to_base_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Purchase UOM to Base UOM', max_digits=10)),
                ('sales_to_base_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Sales UOM to Base UOM', max_digits=10)),
                ('track_inventory', models.BooleanField(default=True)),
                ('track_batches', models.BooleanField(default=False, help_text='Enable batch/lot tracking')),
                ('track_serial_numbers', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('shelf_life_days', models.IntegerField(blank=True, help_text='Shelf life in days', null=True)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, help_text='Standard/Average cost', max_digits=12)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_category', models.CharField(blank=True, max_length=50)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System Code for import/export', max_length=20)),
                ('is_manufactured', models.BooleanField(default=False)),
                ('manufacturing_lead_time_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('is_saleable', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('preferred_vendor', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='partners.businesspartner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_base', to='products.unitofmeasure')),
                ('purchase_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='products.unitofmeasure')),
                ('sales_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_sales', to='products.unitofmeasure')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='e.g., Size: Large, Color: Red', max_length=100)),
                ('variant_code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price difference from base product', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['variant_name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
    ]
