# Generated by Django 5.2.9 on 2025-12-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Product density for volume-weight conversions (e.g., kg/liter)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='density_uom',
            field=models.ForeignKey(blank=True, help_text='Reference UoM for density measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='density_products', to='products.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('simple', 'Simple Multiplier'), ('density', 'Density-based (Volume ↔ Weight)'), ('formula', 'Custom Formula')], default='simple', help_text='Type of conversion calculation', max_length=20)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, help_text='Multiplier for simple conversions (e.g., 1000 for kg to g)', max_digits=10, null=True)),
                ('formula', models.TextField(blank=True, help_text="Python expression for custom conversions. Use 'quantity' as variable.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If true, reverse conversion is automatically available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_uom', models.ForeignKey(help_text='Source unit of measure', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='products.unitofmeasure')),
                ('to_uom', models.ForeignKey(help_text='Target unit of measure', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='products.unitofmeasure')),
            ],
            options={
                'verbose_name': 'UoM Conversion',
                'verbose_name_plural': 'UoM Conversions',
                'ordering': ['from_uom', 'to_uom'],
                'unique_together': {('from_uom', 'to_uom')},
            },
        ),
    ]
