# Generated by Django 6.0 on 2025-12-09 09:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost Center (V2)',
                'verbose_name_plural': 'Cost Centers (V2)',
                'db_table': 'accounting_costcenter_v2',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('is_base_currency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency (V2)',
                'verbose_name_plural': 'Currencies (V2)',
                'db_table': 'accounting_currency_v2',
                'ordering': ['currency_code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department (V2)',
                'verbose_name_plural': 'Departments (V2)',
                'db_table': 'accounting_department_v2',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroupV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax Group (V2)',
                'verbose_name_plural': 'Tax Groups (V2)',
                'db_table': 'accounting_taxgroup_v2',
            },
        ),
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'ordering': ['account_code'], 'verbose_name': 'Chart of Accounts (Legacy)', 'verbose_name_plural': 'Chart of Accounts (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date', '-entry_number'], 'verbose_name_plural': 'Journal Entries (Legacy)'},
        ),
        migrations.AlterModelTable(
            name='accounttype',
            table='accounting_accounttype',
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table='accounting_bankaccount',
        ),
        migrations.AlterModelTable(
            name='chartofaccounts',
            table='accounting_chartofaccounts',
        ),
        migrations.AlterModelTable(
            name='fiscalyear',
            table='accounting_fiscalyear',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='accounting_invoice',
        ),
        migrations.AlterModelTable(
            name='invoiceitem',
            table='accounting_invoiceitem',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='accounting_journalentry',
        ),
        migrations.AlterModelTable(
            name='journalentryline',
            table='accounting_journalentryline',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='accounting_payment',
        ),
        migrations.AlterModelTable(
            name='paymentallocation',
            table='accounting_paymentallocation',
        ),
        migrations.AlterModelTable(
            name='taxcode',
            table='accounting_taxcode',
        ),
        migrations.CreateModel(
            name='AccountV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_group', models.CharField(choices=[('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('investment', 'Investment'), ('other_asset', 'Other Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long Term Liability'), ('other_liability', 'Other Liability'), ('capital', 'Capital'), ('retained_earnings', 'Retained Earnings'), ('drawings', 'Drawings'), ('sales', 'Sales'), ('other_income', 'Other Income'), ('direct_expense', 'Direct Expense'), ('indirect_expense', 'Indirect Expense'), ('operating_expense', 'Operating Expense')], max_length=50)),
                ('is_group', models.BooleanField(default=False, help_text='Group accounts cannot have direct postings')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_direct_posting', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_v2_created', to=settings.AUTH_USER_MODEL)),
                ('migrated_from_legacy', models.ForeignKey(blank=True, help_text='Legacy account this was migrated from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.accountv2')),
            ],
            options={
                'verbose_name': 'Account (V2)',
                'verbose_name_plural': 'Chart of Accounts (V2 - Enhanced)',
                'db_table': 'accounting_account_v2',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxMasterV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=20, unique=True)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales_tax', 'Sales Tax'), ('service_tax', 'Service Tax'), ('excise', 'Excise Duty'), ('customs', 'Customs Duty')], max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_collected_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_collected_for_v2', to='accounting.accountv2')),
                ('tax_paid_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_paid_for_v2', to='accounting.accountv2')),
            ],
            options={
                'verbose_name': 'Tax Master (V2)',
                'verbose_name_plural': 'Tax Masters (V2)',
                'db_table': 'accounting_taxmaster_v2',
                'ordering': ['tax_code'],
            },
        ),
        migrations.CreateModel(
            name='VoucherV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('JE', 'Journal Entry'), ('SI', 'Sales Invoice'), ('PI', 'Purchase Invoice'), ('CPV', 'Cash Payment Voucher'), ('BPV', 'Bank Payment Voucher'), ('CRV', 'Cash Receipt Voucher'), ('BRV', 'Bank Receipt Voucher'), ('DN', 'Debit Note'), ('CN', 'Credit Note'), ('CE', 'Contra Entry')], max_length=10)),
                ('voucher_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_v2_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_v2_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_v2', to='accounting.currencyv2')),
                ('migrated_from_legacy', models.ForeignKey(blank=True, help_text='Legacy journal entry this was migrated from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_v2', to='partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Voucher (V2)',
                'verbose_name_plural': 'Vouchers (V2)',
                'db_table': 'accounting_voucher_v2',
                'ordering': ['-voucher_date', '-voucher_number'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntryV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_entries_v2', to='accounting.accountv2')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries_v2', to='accounting.costcenterv2')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries_v2', to='accounting.departmentv2')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_v2', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'Voucher Entry (V2)',
                'verbose_name_plural': 'Voucher Entries (V2)',
                'db_table': 'accounting_voucherentry_v2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from_v2', to='accounting.currencyv2')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to_v2', to='accounting.currencyv2')),
            ],
            options={
                'verbose_name': 'Exchange Rate (V2)',
                'verbose_name_plural': 'Exchange Rates (V2)',
                'db_table': 'accounting_exchangerate_v2',
                'ordering': ['-rate_date'],
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
        migrations.CreateModel(
            name='TaxGroupItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1)),
                ('apply_on_previous', models.BooleanField(default=False, help_text='Apply this tax on previous tax amount (compound tax)')),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_v2', to='accounting.taxgroupv2')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items_v2', to='accounting.taxmasterv2')),
            ],
            options={
                'verbose_name': 'Tax Group Item (V2)',
                'verbose_name_plural': 'Tax Group Items (V2)',
                'db_table': 'accounting_taxgroupitem_v2',
                'ordering': ['sequence'],
                'unique_together': {('tax_group', 'tax')},
            },
        ),
    ]
