# Generated by Django 5.2.9 on 2025-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_costcenterv2_currencyv2_departmentv2_taxgroupv2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountv2',
            name='ias_reference_code',
            field=models.CharField(blank=True, help_text="IAS/IFRS reference code (e.g., 'IAS 7', 'IFRS 13')", max_length=20),
        ),
        migrations.AddField(
            model_name='accountv2',
            name='ifrs_category',
            field=models.CharField(blank=True, choices=[('financial_assets', 'Financial Assets'), ('financial_liabilities', 'Financial Liabilities'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expenses', 'Expenses'), ('other_comprehensive_income', 'Other Comprehensive Income')], help_text='IFRS financial statement category', max_length=50),
        ),
        migrations.AddField(
            model_name='accountv2',
            name='ifrs_subcategory',
            field=models.CharField(blank=True, help_text='Detailed IFRS classification', max_length=100),
        ),
        migrations.AddField(
            model_name='accountv2',
            name='measurement_basis',
            field=models.CharField(choices=[('cost', 'Historical Cost'), ('fair_value', 'Fair Value'), ('amortized_cost', 'Amortized Cost'), ('net_realizable_value', 'Net Realizable Value'), ('value_in_use', 'Value in Use')], default='cost', help_text='Measurement basis per IFRS', max_length=30),
        ),
    ]
