# Generated by Django 5.2.9 on 2025-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountv2_ias_reference_code_accountv2_ifrs_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountv2',
            name='ias_reference_code',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('IAS 1', 'IAS 1 - Presentation of Financial Statements'), ('IAS 2', 'IAS 2 - Inventories'), ('IAS 7', 'IAS 7 - Statement of Cash Flows'), ('IAS 8', 'IAS 8 - Accounting Policies, Changes in Accounting Estimates and Errors'), ('IAS 10', 'IAS 10 - Events After the Reporting Period'), ('IAS 12', 'IAS 12 - Income Taxes'), ('IAS 16', 'IAS 16 - Property, Plant and Equipment'), ('IAS 17', 'IAS 17 - Leases (Superseded by IFRS 16)'), ('IAS 19', 'IAS 19 - Employee Benefits'), ('IAS 20', 'IAS 20 - Accounting for Government Grants'), ('IAS 21', 'IAS 21 - The Effects of Changes in Foreign Exchange Rates'), ('IAS 23', 'IAS 23 - Borrowing Costs'), ('IAS 24', 'IAS 24 - Related Party Disclosures'), ('IAS 26', 'IAS 26 - Accounting and Reporting by Retirement Benefit Plans'), ('IAS 27', 'IAS 27 - Separate Financial Statements'), ('IAS 28', 'IAS 28 - Investments in Associates and Joint Ventures'), ('IAS 29', 'IAS 29 - Financial Reporting in Hyperinflationary Economies'), ('IAS 32', 'IAS 32 - Financial Instruments: Presentation'), ('IAS 33', 'IAS 33 - Earnings per Share'), ('IAS 34', 'IAS 34 - Interim Financial Reporting'), ('IAS 36', 'IAS 36 - Impairment of Assets'), ('IAS 37', 'IAS 37 - Provisions, Contingent Liabilities and Contingent Assets'), ('IAS 38', 'IAS 38 - Intangible Assets'), ('IAS 39', 'IAS 39 - Financial Instruments: Recognition and Measurement (Superseded by IFRS 9)'), ('IAS 40', 'IAS 40 - Investment Property'), ('IAS 41', 'IAS 41 - Agriculture'), ('IFRS 1', 'IFRS 1 - First-time Adoption of IFRS'), ('IFRS 2', 'IFRS 2 - Share-based Payment'), ('IFRS 3', 'IFRS 3 - Business Combinations'), ('IFRS 4', 'IFRS 4 - Insurance Contracts'), ('IFRS 5', 'IFRS 5 - Non-current Assets Held for Sale and Discontinued Operations'), ('IFRS 6', 'IFRS 6 - Exploration for and Evaluation of Mineral Resources'), ('IFRS 7', 'IFRS 7 - Financial Instruments: Disclosures'), ('IFRS 8', 'IFRS 8 - Operating Segments'), ('IFRS 9', 'IFRS 9 - Financial Instruments'), ('IFRS 10', 'IFRS 10 - Consolidated Financial Statements'), ('IFRS 11', 'IFRS 11 - Joint Arrangements'), ('IFRS 12', 'IFRS 12 - Disclosure of Interests in Other Entities'), ('IFRS 13', 'IFRS 13 - Fair Value Measurement'), ('IFRS 14', 'IFRS 14 - Regulatory Deferral Accounts'), ('IFRS 15', 'IFRS 15 - Revenue from Contracts with Customers'), ('IFRS 16', 'IFRS 16 - Leases'), ('IFRS 17', 'IFRS 17 - Insurance Contracts')], help_text='IAS/IFRS reference code', max_length=20),
        ),
    ]
