# Generated by Django 5.2.9 on 2025-12-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_accountv2_ias_reference_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FairValueMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(help_text='Date of fair value measurement')),
                ('measurement_purpose', models.CharField(choices=[('initial_recognition', 'Initial Recognition'), ('subsequent_measurement', 'Subsequent Measurement'), ('revaluation', 'Revaluation'), ('impairment_testing', 'Impairment Testing'), ('disposal', 'Disposal')], default='subsequent_measurement', help_text='Purpose of this measurement', max_length=30)),
                ('fair_value_level', models.CharField(choices=[('level_1', 'Level 1 - Quoted prices in active markets'), ('level_2', 'Level 2 - Observable inputs other than quoted prices'), ('level_3', 'Level 3 - Unobservable inputs')], help_text='IFRS 13 fair value hierarchy level', max_length=10)),
                ('valuation_technique', models.CharField(choices=[('market_approach', 'Market Approach'), ('income_approach', 'Income Approach (DCF, etc.)'), ('cost_approach', 'Cost Approach (Replacement Cost)')], help_text='Valuation technique used', max_length=20)),
                ('valuation_description', models.TextField(blank=True, help_text='Detailed description of valuation methodology')),
                ('inputs_used', models.JSONField(default=dict, help_text='Key inputs used in valuation (JSON format)')),
                ('fair_value', models.DecimalField(decimal_places=2, help_text='Fair value amount', max_digits=15)),
                ('carrying_amount', models.DecimalField(decimal_places=2, help_text='Carrying amount before fair value adjustment', max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, help_text='Fair value gain/(loss) = Fair Value - Carrying Amount', max_digits=15)),
                ('recognized_in_pl', models.BooleanField(default=True, help_text='Gain/loss recognized in Profit & Loss (vs. OCI)')),
                ('external_valuer', models.CharField(blank=True, help_text='Name of external valuer (if applicable)', max_length=200)),
                ('valuer_credentials', models.CharField(blank=True, help_text='Professional credentials of valuer', max_length=200)),
                ('valuation_report_ref', models.CharField(blank=True, help_text='Reference number of valuation report', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or assumptions')),
                ('account', models.ForeignKey(help_text='Account being measured (e.g., Investment Property, Financial Asset)', on_delete=django.db.models.deletion.PROTECT, related_name='fair_value_measurements', to='accounting.accountv2')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_value_measurements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_value_measurements_created', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, help_text='Voucher created for fair value adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_value_adjustments', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'Fair Value Measurement',
                'verbose_name_plural': 'Fair Value Measurements',
                'db_table': 'accounting_fairvaluemeasurement',
                'ordering': ['-measurement_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'measurement_date'], name='accounting__account_08e539_idx'), models.Index(fields=['fair_value_level'], name='accounting__fair_va_ba33c5_idx'), models.Index(fields=['measurement_date'], name='accounting__measure_6dce72_idx')],
            },
        ),
    ]
