# Generated by Django 5.2.9 on 2025-12-29 15:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fairvaluemeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_code', models.CharField(help_text='Unique entity code (e.g., HQ, SUB01, BR-US)', max_length=20, unique=True)),
                ('entity_name', models.CharField(help_text='Full legal name of the entity', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Short name for display', max_length=50)),
                ('country', models.CharField(help_text='Country of operation', max_length=100)),
                ('consolidation_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Ownership percentage for consolidation (0-100)', max_digits=5)),
                ('consolidation_method', models.CharField(choices=[('full', 'Full Consolidation (>50% ownership)'), ('proportionate', 'Proportionate Consolidation'), ('equity', 'Equity Method (20-50% ownership)'), ('none', 'No Consolidation (<20% ownership)')], default='full', help_text='Consolidation method per IFRS 10/IAS 28', max_length=20)),
                ('eliminate_intercompany', models.BooleanField(default=True, help_text='Eliminate intercompany transactions in consolidation')),
                ('entity_type', models.CharField(choices=[('parent', 'Parent Company'), ('subsidiary', 'Subsidiary'), ('branch', 'Branch'), ('joint_venture', 'Joint Venture'), ('associate', 'Associate')], default='subsidiary', help_text='Type of entity in group structure', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether entity is currently active')),
                ('activation_date', models.DateField(blank=True, help_text='Date entity became active', null=True)),
                ('deactivation_date', models.DateField(blank=True, help_text='Date entity was deactivated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this entity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_created', to=settings.AUTH_USER_MODEL)),
                ('functional_currency', models.ForeignKey(help_text='Functional currency per IAS 21 (currency of primary economic environment)', on_delete=django.db.models.deletion.PROTECT, related_name='entities_functional', to='accounting.currencyv2')),
                ('parent_entity', models.ForeignKey(blank=True, help_text='Parent entity for consolidation hierarchy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='accounting.entity')),
                ('presentation_currency', models.ForeignKey(blank=True, help_text='Presentation currency for reporting (if different from functional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities_presentation', to='accounting.currencyv2')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'accounting_entity',
                'ordering': ['entity_code'],
                'indexes': [models.Index(fields=['entity_code'], name='accounting__entity__2aa007_idx'), models.Index(fields=['parent_entity'], name='accounting__parent__ba97ee_idx'), models.Index(fields=['functional_currency'], name='accounting__functio_4114a5_idx')],
            },
        ),
    ]
