# Generated by Django 5.2.9 on 2025-12-29 15:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FXRevaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_id', models.CharField(help_text='Unique identifier for this revaluation run', max_length=50, unique=True)),
                ('revaluation_date', models.DateField(help_text='Date of revaluation (usually month-end)')),
                ('accounts_revalued', models.IntegerField(default=0, help_text='Number of accounts revalued')),
                ('total_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total unrealized FX gain', max_digits=15)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total unrealized FX loss', max_digits=15)),
                ('net_fx_gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net FX gain/(loss)', max_digits=15)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('calculated', 'Calculated'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('error', 'Error')], default='initiated', help_text='Status of this revaluation', max_length=20)),
                ('execution_method', models.CharField(default='manual', help_text='How was this revaluation triggered (manual, scheduled, api)', max_length=50)),
                ('auto_posted', models.BooleanField(default=False, help_text='Whether entries were automatically posted')),
                ('reversal_created', models.BooleanField(default=False, help_text='Whether reversal entry was created')),
                ('revaluation_details', models.JSONField(default=dict, help_text='Detailed revaluation results per account (JSON format)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if revaluation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this revaluation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluation_logs_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(help_text='Entity being revalued', on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluation_logs', to='accounting.entity')),
                ('functional_currency', models.ForeignKey(help_text='Functional currency of the entity', on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluation_logs', to='accounting.currencyv2')),
                ('reversal_voucher', models.ForeignKey(blank=True, help_text='Reversal voucher (if created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluation_reversal_logs', to='accounting.voucherv2')),
                ('voucher', models.ForeignKey(blank=True, help_text='Voucher created for this revaluation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluation_logs', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'FX Revaluation Log',
                'verbose_name_plural': 'FX Revaluation Logs',
                'db_table': 'accounting_fx_revaluation_log',
                'ordering': ['-revaluation_date', '-created_at'],
                'indexes': [models.Index(fields=['entity', 'revaluation_date'], name='accounting__entity__80b255_idx'), models.Index(fields=['revaluation_id'], name='accounting__revalua_5a6c2e_idx'), models.Index(fields=['status'], name='accounting__status_74103b_idx'), models.Index(fields=['revaluation_date'], name='accounting__revalua_ecabf7_idx')],
            },
        ),
    ]
