# Generated by Django 5.2.9 on 2025-12-29 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_fxrevaluationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(help_text='Human-readable name for this numbering scheme', max_length=100)),
                ('document_type', models.CharField(choices=[('voucher', 'Voucher'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('journal', 'Journal Entry'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('quotation', 'Quotation'), ('delivery_note', 'Delivery Note'), ('goods_receipt', 'Goods Receipt'), ('custom', 'Custom Document')], help_text='Type of document this scheme applies to', max_length=50)),
                ('prefix', models.CharField(blank=True, help_text="Static prefix (e.g., 'INV', 'VCH')", max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='Static suffix (optional)', max_length=20)),
                ('date_format', models.CharField(blank=True, choices=[('', 'No Date'), ('YYYY', 'Year (2025)'), ('YY', 'Year Short (25)'), ('YYMM', 'Year-Month (2501)'), ('YYYYMM', 'Year-Month (202501)'), ('YYMMDD', 'Year-Month-Day (250129)'), ('YYYYMMDD', 'Year-Month-Day (20250129)')], default='', help_text='Date format to include in number', max_length=20)),
                ('separator', models.CharField(default='-', help_text='Separator character between components', max_length=5)),
                ('padding', models.IntegerField(default=4, help_text='Number of digits for sequence (e.g., 4 = 0001)')),
                ('next_number', models.IntegerField(default=1, help_text='Next number in sequence')),
                ('reset_frequency', models.CharField(choices=[('never', 'Never Reset'), ('yearly', 'Reset Yearly'), ('monthly', 'Reset Monthly'), ('daily', 'Reset Daily')], default='yearly', help_text='When to reset the counter', max_length=20)),
                ('last_reset_date', models.DateField(blank=True, help_text='Date when counter was last reset', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scheme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this numbering scheme')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbering_schemes_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, help_text='Specific entity (leave blank for global scheme)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbering_schemes', to='accounting.entity')),
            ],
            options={
                'verbose_name': 'Numbering Scheme',
                'verbose_name_plural': 'Numbering Schemes',
                'db_table': 'accounting_numbering_scheme',
                'ordering': ['document_type', 'scheme_name'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='accounting__documen_12bde3_idx'), models.Index(fields=['entity', 'document_type'], name='accounting__entity__a6eb23_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type', 'entity'), name='unique_active_scheme_per_entity'), models.UniqueConstraint(condition=models.Q(('entity__isnull', True), ('is_active', True)), fields=('document_type',), name='unique_active_global_scheme')],
            },
        ),
    ]
