# Generated by Django 5.2.9 on 2025-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_numberingscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_references',
            field=models.JSONField(blank=True, default=dict, help_text='Custom user-defined references'),
        ),
        migrations.AddField(
            model_name='voucherv2',
            name='user_references',
            field=models.JSONField(blank=True, default=dict, help_text='Custom user-defined references'),
        ),
    ]
