# Generated by Django 5.2.9 on 2025-12-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_invoice_user_references_voucherv2_user_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('voucher', 'Voucher'), ('invoice', 'Invoice')], max_length=50)),
                ('field_key', models.CharField(help_text='Key used in the JSON data', max_length=50)),
                ('field_label', models.CharField(help_text='User-facing label', max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_regex', models.CharField(blank=True, help_text='Optional regex for text fields', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_name', 'field_label'],
                'unique_together': {('model_name', 'field_key')},
            },
        ),
    ]
