# Generated by Django 5.2.9 on 2025-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_referencedefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedefinition',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='Enforce uniqueness for this field value'),
        ),
    ]
