# Generated by Django 5.2.9 on 2025-12-30 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_referencedefinition_is_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model that was changed', max_length=100)),
                ('object_id', models.IntegerField(db_index=True, help_text='ID of the object that was changed')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Type of action performed', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user')),
                ('changes', models.JSONField(default=dict, help_text='Before and after values in JSON format')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the change')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'accounting_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='accounting__model_n_d0095a_idx'), models.Index(fields=['model_name', 'object_id', 'timestamp'], name='accounting__model_n_279f61_idx'), models.Index(fields=['user', 'timestamp'], name='accounting__user_id_d31988_idx')],
            },
        ),
    ]
