# Generated by Django 5.2.9 on 2025-12-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, help_text='Closing balance as per Bank Statement', max_digits=15)),
                ('ledger_balance', models.DecimalField(decimal_places=2, help_text='Closing balance as per System Ledger', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, help_text='Should be zero for successful reconciliation', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.accountv2')),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(help_text='Date of statement generation')),
                ('start_date', models.DateField(help_text='Period start date')),
                ('end_date', models.DateField(help_text='Period end date')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='bank_statements/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(help_text='The general ledger account representing this bank account', on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.accountv2')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Running balance provided by bank', max_digits=15)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('matched_voucher_line', models.ForeignKey(blank=True, help_text='The ledger entry this bank line matches to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='accounting.voucherentryv2')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
        ),
    ]
