# Generated by Django 5.2.9 on 2025-12-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_bankreconciliation_bankstatement_bankstatementline'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(help_text='Unique cheque number', max_length=50, unique=True)),
                ('cheque_date', models.DateField(help_text='Date on the cheque')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cheque amount', max_digits=15)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled'), ('bounced', 'Bounced')], default='issued', help_text='Current status of the cheque', max_length=20)),
                ('clearance_date', models.DateField(blank=True, help_text='Date when cheque was cleared by bank', null=True)),
                ('is_post_dated', models.BooleanField(default=False, help_text='Is this a post-dated cheque?')),
                ('cancelled_date', models.DateField(blank=True, help_text='Date when cheque was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account from which cheque is issued', on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounting.accountv2')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques_created', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(help_text='Payee (recipient) of the cheque', on_delete=django.db.models.deletion.PROTECT, related_name='cheques_received', to='partners.businesspartner')),
                ('voucher', models.ForeignKey(blank=True, help_text='Linked payment voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-cheque_date', '-created_at'],
                'indexes': [models.Index(fields=['cheque_number'], name='accounting__cheque__dbc39f_idx'), models.Index(fields=['status'], name='accounting__status_cdb466_idx'), models.Index(fields=['cheque_date'], name='accounting__cheque__319815_idx'), models.Index(fields=['bank_account', 'status'], name='accounting__bank_ac_36206f_idx')],
            },
        ),
    ]
