# Generated by Django 5.2.9 on 2025-12-30 17:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_cheque_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(help_text='Unique transfer number', max_length=50, unique=True)),
                ('transfer_date', models.DateField(help_text='Date of transfer')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount in source currency', max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Exchange rate (1 source currency = X destination currency)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the transfer', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the transfer', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Transfer description or notes')),
                ('reference', models.CharField(blank=True, help_text='External reference number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_bank', models.ForeignKey(help_text='Source bank account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='accounting.accountv2')),
                ('from_currency', models.ForeignKey(help_text='Source currency', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from_currency', to='accounting.currencyv2')),
                ('to_bank', models.ForeignKey(help_text='Destination bank account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='accounting.accountv2')),
                ('to_currency', models.ForeignKey(help_text='Destination currency', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to_currency', to='accounting.currencyv2')),
                ('voucher', models.ForeignKey(blank=True, help_text='Linked accounting voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['transfer_number'], name='accounting__transfe_301fde_idx'), models.Index(fields=['status'], name='accounting__status_3dbba1_idx'), models.Index(fields=['approval_status'], name='accounting__approva_ff322f_idx'), models.Index(fields=['transfer_date'], name='accounting__transfe_3f0337_idx'), models.Index(fields=['from_bank', 'to_bank'], name='accounting__from_ba_c7cca8_idx')],
            },
        ),
    ]
