# Generated by Django 6.0 on 2025-12-31 16:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_bank_transfer_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(help_text='Unique category code (e.g., BLDG, MACH, VEH)', max_length=20, unique=True)),
                ('category_name', models.CharField(help_text='Category name (e.g., Buildings, Machinery, Vehicles)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of asset category')),
                ('useful_life_years', models.IntegerField(help_text='Estimated useful life in years (IAS 16.56)', validators=[django.core.validators.MinValueValidator(1)])),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], default='straight_line', help_text='Depreciation method per IAS 16.60', max_length=30)),
                ('residual_value_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Residual value as percentage of cost (IAS 16.6)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ias_reference_code', models.CharField(default='IAS 16', help_text='IAS/IFRS reference code', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'accounting_asset_category',
                'ordering': ['category_code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(help_text='Unique asset number (e.g., FA-2025-001)', max_length=50, unique=True)),
                ('asset_name', models.CharField(help_text='Asset name/description', max_length=200)),
                ('acquisition_date', models.DateField(help_text='Date of acquisition (IAS 16.16)')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Initial cost including purchase price and directly attributable costs (IAS 16.16)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total depreciation charged to date (IAS 16.6)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location', models.CharField(help_text='Physical location of asset', max_length=200)),
                ('asset_tag', models.CharField(help_text='Physical asset tag/barcode for identification', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', help_text='Current status of asset', max_length=20)),
                ('disposal_date', models.DateField(blank=True, help_text='Date of disposal (IAS 16.67)', null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Disposal proceeds (IAS 16.71)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_category', models.ForeignKey(help_text='Asset category', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounting.assetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets_created', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(blank=True, help_text='General ledger account for this asset (IAS 16 compliant)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.accountv2')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'db_table': 'accounting_fixed_asset',
                'ordering': ['asset_number'],
                'indexes': [models.Index(fields=['asset_number'], name='accounting__asset_n_72b376_idx'), models.Index(fields=['asset_tag'], name='accounting__asset_t_0f48bf_idx'), models.Index(fields=['status'], name='accounting__status_ee2f25_idx'), models.Index(fields=['asset_category', 'status'], name='accounting__asset_c_ab86e7_idx')],
            },
        ),
    ]
