# Generated by Django 6.0 on 2026-01-10 15:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_fixed_asset_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity (V2)',
                'verbose_name_plural': 'Entities (V2)',
                'db_table': 'accounting_entity_v2',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(help_text='Name of the approval workflow', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the workflow')),
                ('document_type', models.CharField(choices=[('voucher', 'Voucher'), ('purchase_order', 'Purchase Order'), ('purchase_requisition', 'Purchase Requisition'), ('sales_order', 'Sales Order'), ('sales_quotation', 'Sales Quotation'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('bank_transfer', 'Bank Transfer'), ('journal_entry', 'Journal Entry'), ('asset_acquisition', 'Asset Acquisition'), ('asset_disposal', 'Asset Disposal'), ('budget', 'Budget'), ('other', 'Other')], help_text='Type of document this workflow applies to', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'accounting_approvalworkflow',
                'ordering': ['workflow_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text="Type of document (e.g., 'voucher', 'purchase_order')", max_length=50)),
                ('document_id', models.IntegerField(help_text='ID of the document being approved')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the document', max_digits=15)),
                ('current_level', models.IntegerField(default=1, help_text='Current approval level')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='When the approval was requested')),
                ('completion_date', models.DateTimeField(blank=True, help_text='When the approval was completed (approved/rejected)', null=True)),
                ('current_approver', models.ForeignKey(blank=True, help_text='Current approver', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_pending', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who initiated the approval request', on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounting.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'accounting_approvalrequest',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(help_text='Approval level number (1 = first level)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount for this level', max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('999999999.99'), help_text='Maximum amount for this level', max_digits=15)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this level is mandatory')),
                ('approver', models.ForeignKey(help_text='User who approves at this level', on_delete=django.db.models.deletion.PROTECT, related_name='approval_levels', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='accounting.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'db_table': 'accounting_approvallevel',
                'ordering': ['workflow', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(help_text='Approval level number')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('returned', 'Returned for Revision')], help_text='Action taken by approver', max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Approver's comments")),
                ('action_date', models.DateTimeField(auto_now_add=True, help_text='When the action was taken')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the approver')),
                ('approver', models.ForeignKey(help_text='User who took this action', on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='accounting.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'accounting_approvalaction',
                'ordering': ['approval_request', 'level_number', 'action_date'],
                'indexes': [models.Index(fields=['approval_request', 'level_number'], name='accounting__approva_fdf94e_idx'), models.Index(fields=['approver', 'action_date'], name='accounting__approve_3c3e7f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['document_type', 'is_active'], name='accounting__documen_be63b4_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['document_type', 'document_id'], name='accounting__documen_fc2aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='accounting__status_cf8454_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['current_approver', 'status'], name='accounting__current_32db42_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester'], name='accounting__request_b05da2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallevel',
            index=models.Index(fields=['workflow', 'level_number'], name='accounting__workflo_238567_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallevel',
            index=models.Index(fields=['approver'], name='accounting__approve_76c486_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('workflow', 'level_number')},
        ),
    ]
