# Generated by Django 6.0 on 2026-01-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_entityv2_approvalworkflow_approvalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherv2',
            name='approval_request',
            field=models.ForeignKey(blank=True, help_text='Linked approval request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_v2', to='accounting.approvalrequest'),
        ),
        migrations.AddField(
            model_name='voucherv2',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_required', help_text='Approval workflow status (IAS 1 - Internal Controls)', max_length=20),
        ),
    ]
