# Generated by Django 6.0 on 2026-01-10 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_voucherv2_approval_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Short-lived access token')),
                ('refresh_token_encrypted', models.BinaryField(help_text='Encrypted refresh token')),
                ('token_expiry', models.DateTimeField(help_text='When the access token expires')),
                ('email', models.EmailField(help_text='The Gmail address associated with this token', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gmail Token',
                'verbose_name_plural': 'User Gmail Tokens',
                'db_table': 'accounting_usergmailtoken',
            },
        ),
        migrations.CreateModel(
            name='EmailCommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Gmail Message ID', max_length=255, unique=True)),
                ('subject', models.CharField(help_text='Email Subject', max_length=998)),
                ('sender', models.EmailField(help_text='Sender Email', max_length=254)),
                ('recipient', models.TextField(help_text='Recipient Email(s)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', help_text='Status (sent, failed)', max_length=50)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata (labels, threadId)')),
                ('approval_action', models.ForeignKey(blank=True, help_text='Related Approval Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='accounting.approvalaction')),
                ('voucher', models.ForeignKey(blank=True, help_text='Related Voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='accounting.voucherv2')),
            ],
            options={
                'verbose_name': 'Email Communication Log',
                'verbose_name_plural': 'Email Communication Logs',
                'db_table': 'accounting_emailcommunicationlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='accounting__timesta_872a51_idx'), models.Index(fields=['sender'], name='accounting__sender_6c98a4_idx'), models.Index(fields=['voucher'], name='accounting__voucher_8924ac_idx')],
            },
        ),
    ]
