# Generated by Django 6.0 on 2026-01-10 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_usergmailtoken_emailcommunicationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('journal_entry', 'Journal Entry')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField(help_text='Next scheduled run date')),
                ('template_data', models.JSONField(help_text='JSON template for the voucher/document')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=False, help_text='Automatically post the generated document?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurring Transaction',
                'verbose_name_plural': 'Recurring Transactions',
                'ordering': ['next_run_date'],
            },
        ),
    ]
