# Generated by Django 6.0 on 2026-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails for notifications'),
        ),
    ]
