# Generated by Django 6.0 on 2026-01-10 21:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_budget_budgetline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenterv2',
            name='budget_allocation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='costcenterv2',
            name='is_profit_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costcenterv2',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL),
        ),
    ]
