# Generated by Django 6.0 on 2025-12-09 09:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('semi_finished', 'Semi-Finished'), ('consumable', 'Consumable')], default='raw_material', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Expected scrap/waste percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('sequence', models.IntegerField(default=10, help_text='Order of addition in manufacturing')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sequence', 'product'],
            },
        ),
        migrations.CreateModel(
            name='BOMOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10)),
                ('operation_name', models.CharField(max_length=100)),
                ('setup_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('run_time_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Time per unit', max_digits=8)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_type', models.CharField(choices=[('breakdown', 'Machine Breakdown'), ('maintenance', 'Scheduled Maintenance'), ('material_shortage', 'Material Shortage'), ('power_failure', 'Power Failure'), ('other', 'Other')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('rejected_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('planned_start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.IntegerField(default=5, help_text='1=Highest, 10=Lowest')),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('estimated_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=100)),
                ('check_type', models.CharField(blank=True, help_text='e.g., Visual, Chemical, Physical', max_length=50)),
                ('parameter_name', models.CharField(blank=True, max_length=100)),
                ('expected_value', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('tolerance', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['checked_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Production capacity per hour', max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Cost per hour', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('bom_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('assembly', 'Assembly'), ('disassembly', 'Disassembly')], default='manufacturing', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Output quantity for this BOM', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default BOM for this product')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['-is_default', 'product', 'version'],
            },
        ),
    ]
