# Generated by Django 6.0 on 2025-12-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_manufactured': True}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterials'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='bomoperation',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='manufacturing.billofmaterials'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='consumed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='products.product'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productiondowntime',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_downtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.billofmaterials'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='products.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productiondowntime',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.productionorder'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='capacity_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centers', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productiondowntime',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='manufacturing.workcenter'),
        ),
        migrations.AddField(
            model_name='bomoperation',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='manufacturing.workcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('product', 'version')},
        ),
    ]
